[package]
name = "cadency_codegen"
version = "0.3.0"
edition = "2021"
description = "Library with codegen macros for the cadency discord bot"
license = "MIT"
repository = "https://github.com/jontze/cadency-rs"

[lib]
proc_macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.23"
syn = "1.0.107"
