[package]
name = "cadency_commands"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
reqwest = "0.11.6"

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.serenity]
version = "0.11.5"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "voice", "cache"]

[dependencies.songbird]
version = "0.3.0"
features = ["builtin-queue"]

[dependencies.cadency_core]
path = "../cadency_core"

[dependencies.cadency_derive]
path = "../cadency_derive"
