name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  test_release:
    name: Test Main
    uses: ./.github/workflows/test.yml

  publish_image:
    needs:
      - test_release
    name: Publish main image
    uses: ./.github/workflows/image.yml
    with:
      push: true
    secrets:
      GHCR_USER: ${{ secrets.GHCR_USER }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
