name: Cargo Audit
on:
  schedule:
    - cron: 0 8 * * 1,3,5 # At 08:00 on Monday, Wednesday, and Friday

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
